[package]
name = "fractals"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.0"
num = "0.4.0"
colorgrad = "0.5.0"
rayon = "1.5.1"