[package]
name = "fractals"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colorgrad = "0.6.2"
image = "0.24.6"
num = "0.4.0"
rayon = "1.7.0"
